[tool.poetry]

name = "memegen"
version = "6.2"
description = "The open source meme generator."
authors = ["Jace Browning <support@maketested.com>"]
license = "MIT"

packages = [ { include = "app" } ]

[tool.poetry.dependencies]

python = "^3.9"

# Sanic
sanic = "~20.9.0"
sanic-cors = "~0.10.0"
sanic-openapi = "~0.6.2"
sanic-jinja2 = "~0.8.0"

# Markdown
markdown = "~3.2.2"
pygments = "^2.7.0"

# Images
pillow = "^8.0.1"
spongemock = "~0.3.4"

# Utilities
aiohttp = "^3.6.2"
datafiles = "~0.12b1"
minilog = "^2.0"

# Production
bugsnag = "^4.0"
gunicorn = "~20.0.4"
uvicorn = "~0.11.8"

[tool.poetry.dev-dependencies]

# Formatting
isort = "=5.5.1"
black = "=20.8b1"

# Type Checking
mypy = "*"
autoflake = "^1.3.1"

# Testing
pytest = "^6.0"
pytest-asyncio = "*"
pytest-describe = { git = "https://github.com/pytest-dev/pytest-describe", rev = "9014bf3ee564518aad3622b5f035f7ca6139e398" }
pytest-expecter = "^2.1"
pytest-random = "*"
pytest-rerunfailures = "^9.1"
pytest-cov = "^2.7"
locust = "^1.2.3"

# Coverage
coveragespace = "^3.1.1"

# Documentation
portray = "^1.4.0"

# Utilities
ipdb = "*"
rope = "^0.14.0"
watchdog = { version = "*", extras = ["watchmedo"] }

[tool.black]

quiet = true

[tool.pytest.ini_options]

testpaths = "app"

addopts = """
--no-header \
--random \
--cov=app --cov-report=term-missing:skip-covered --cov-report=html --no-cov-on-fail
"""

cache_dir = ".cache"

markers = "slow"

[tool.portray]

modules = ["app"]
extra_dirs = ["app/static"]
include_reference_documentation = false

[tool.portray.mkdocs]

site_name = "memegen.link"
markdown_extensions = ["pymdownx.magiclink"]

[tool.portray.mkdocs.theme]

name = "material"
logo = "app/static/favicon.ico"
favicon = "app/static/favicon.ico"
palette = { primary = "black" }

[build-system]

requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
