version: 2

jobs:
  build:
    working_directory: ~/memegen

    docker:
      - image: circleci/python:3.9

    steps:
      - checkout

      - run:
          name: Checking system dependencies
          command: make doctor

      - type: cache-restore
        key: poetry-{{ checksum "poetry.lock" }}

      - run:
          name: Installing project dependencies
          command: make install

      - type: cache-save
        key: poetry-{{ checksum "poetry.lock" }}
        paths:
          - .venv

      - run:
          name: Checking code
          command: make check

      - run:
          name: Running tests
          command: make test && sudo pip install coveralls && coveralls

      - store_test_results:
          path: results

      - store_artifacts:
          path: htmlcov

      - run:
          name: Building site
          command: make site
